# Overall title for pages.
title: "Strom Phylogenetics C++ Tutorial"

#plugins: ['jekyll/scholar', 'jemoji']
plugins: ['jemoji']

baseurl: '/people/plewis/cpp'

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      code_layout: default

#scholar:
#  bibliography_template: bib
#  style: systematic-biology
#  sort_by: author
#  order: ascending

# Conversion
#kramdown:
#  syntax_highlighter: rouge

sass:
  sass_dir: assets/_scss

